### ISSUE TITLE
这个为啥没有内容呢？最近发现这个挺好玩，求分析mini版本的pcb

### ISSUE THREAD

**Issue by zouzhe1** [wherelse/miniAWTRIX#1]
谢谢了

**Comment by wherelse** [comment]
最近太忙了，没来得及把文件上传，包括灯板PCB，外壳设计图纸和主控PCB都有

**Comment by achenakid** [comment]
你好，感谢分享。我想请教下灯板PCB上的WS2812灯珠是用什么规格的。谢谢！！

**Comment by wherelse** [comment]
> 你好，感谢分享。我想请教下灯板PCB上的WS2812灯珠是用什么规格的。谢谢！！

3528规格，现在主分支的灯板PCB可以直接打样使用，没问题的，控制板的PCB文件我做了更改一直没有测试

**Comment by achenakid** [comment]
感谢回复，灯板背面的电容可以不焊吗？如果需要的话，使用什么规格的呢？
再次感谢

**Comment by wherelse** [comment]
> 感谢回复，灯板背面的电容可以不焊吗？如果需要的话，使用什么规格的呢？
> 再次感谢

背面的电容可以不焊，我是没有焊的，没啥问题，规格是0603 104
